name: Build LaTeX document

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LaTeX and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-lang-spanish \
          texlive-science \
          latexmk \
          lmodern \
          texlive-xetex

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdf
        path: main.pdf
